"""Note del relatore per la presentazione alla scuola «Rotta verso la Patente Nautica da Diporto» (circa 8 minuti)."""
import os, re, sys
SP=os.path.dirname(os.path.abspath(__file__))
P=sys.argv[1] if len(sys.argv)>1 else SP+'/deck/project'
N={
'cover':"[40 secondi · minuto 0:40] Buongiorno e grazie del tempo. Sono Fabrizio Fiorucci, skipper e istruttore di vela. Vi presento «Rotta verso la Patente Nautica da Diporto», un corso completo per la patente vela e motore senza limiti dalla costa, pronto da usare subito in aula e in barca. Cinque numeri per inquadrarlo: 30 ore di lezione, 15 lezioni, 13 appendici di ripasso, tutti i 135 esercizi di carteggio d'esame svolti, e oltre mille slide già illustrate. In sette slide vi mostro com'è costruito, a chi serve e perché può funzionare bene nella vostra scuola.",
'rotta':"[70 secondi · minuto 1:50] Il corso è pensato come una rotta in tre tappe, e ogni tappa porta dritta all'esame. La prima, lezioni da 1 a 9, 18 ore, porta alla patente entro 12 miglia: dallo scafo e dai motori agli ormeggi e alle carte, all'ancoraggio, al punto nave e ai fanali, al segnalamento e alla sicurezza, al meteo e alla normativa, fino alla lezione 8 con le emergenze e la prova di carteggio entro 12 miglia sugli esercizi ufficiali. La vela è tutta nella lezione 9, così chi fa solo motore la salta. La seconda, lezioni da 10 a 15, 12 ore: il carteggio senza limiti. Qui la scelta è netta: svolgiamo in aula tutti i 135 esercizi ufficiali, sulle carte 5/D e 42/D, divisi per famiglie: costiera, carburante, scarroccio e correnti. La terza tappa porta verso l'esame: 13 appendici, 20 prove d'esame simulate complete, dieci entro e dieci oltre 12 miglia, il ripasso della prova pratica in barca e le schede riassuntive per studiare a casa. Il programma segue l'Allegato A del decreto ministeriale 323 del 2021, cioè il programma d'esame ufficiale.",
'percorsi':"[80 secondi · minuto 3:10] Un corso, due patenti. Chi vuole la patente entro 12 miglia fa le lezioni da 1 a 9, 18 ore: teoria, emergenze, il carteggio sulla carta 5/D che si prova nella lezione 8 e la vela nella 9; con il solo motore le lezioni da 1 a 8, 16 ore. All'esame ha 5 quesiti di carteggio, sulla carta 5/D, in 20 minuti con al massimo 1 errore, i 20 quiz base in 30 minuti con al massimo 4 errori e, se prende anche la vela, 5 quiz vela in 15 minuti. La prova pratica si può svolgere anche su un lago navigabile. Chi punta al senza limiti segue tutte le 15 lezioni, 30 ore, o 28 con il solo motore. La differenza vera è il carteggio: non più quiz, ma una prova di 4 esercizi sulla carta in 60 minuti, con al massimo un errore. Per questo aggiungiamo le lezioni dalla 10 alla 15, i 135 esercizi svolti e dieci prove simulate dedicate. La prova pratica si fa in mare. E chi ha già la 12 miglia? Non rifà i quiz base: gli bastano il carteggio, più il quiz vela se vuole la vela, cioè le lezioni da 10 a 15. Per la scuola vuol dire poter offrire più percorsi con lo stesso materiale.",
'velamotore':"[70 secondi · minuto 4:20] Seconda scelta per l'allievo: vela e motore, oppure solo motore. Con il solo motore l'esame scritto comprende carteggio e quiz base, senza quiz vela; la pratica è a motore: ormeggio e disormeggio, uomo a mare, nodi, uso degli strumenti. In aula si seguono tutte le lezioni tranne la 9 sulla vela: 16 ore per la patente entro 12 miglia, 28 per quella senza limiti. Con vela e motore si aggiungono i 5 quiz vela, 15 minuti con al massimo un errore, e la pratica comprende andature e manovre a vela oltre a tutto il programma a motore, con l'istruttore di vela a bordo. In aula anche la lezione 9 e l'appendice sui nomi della barca a vela: 18 ore entro 12 miglia, 30 senza limiti. E se la prova a vela non va? L'allievo può scegliere la patente a solo motore facendo le manovre a motore: non perde l'esame. Anche qui, lo stesso materiale serve entrambi i percorsi.",
'allievi':"[70 secondi · minuto 5:30] Che cosa sapranno fare gli allievi alla fine? Sei competenze. Conoscere la barca: scafo, motori, elica, timone, attrezzatura e vele, ogni parte con il suo nome e la sua funzione. Navigare sicuri: precedenze, fanali, segnali sonori e segnalamento, sapere chi passa e dove. Fare il carteggio: punto nave, prora e rotta, carburante, scarroccio e correnti sulle due carte d'esame. Leggere il tempo: pressione, venti e brezze, fronti, onde e bollettini, per decidere se e quando uscire. Gestire l'emergenza: uomo a mare, falla, incendio, abbandono, radio VHF e MAYDAY, sapendo cosa fare e in che ordine. E comandare la barca: manovre, ormeggio e ancoraggio, nodi, documenti, dotazioni e responsabilità del comandante. Il nostro obiettivo non è solo passare l'esame: è uscire in mare sapendo cosa fare.",
'materiale':"[70 secondi · minuto 6:40] Il materiale è già tutto pronto: oltre mille slide illustrate, ognuna con le note per l'istruttore. Quindici lezioni da due ore, 594 slide con disegni originali, schemi e quiz ufficiali seguiti dalle risposte. I 135 esercizi di carteggio, tutti svolti: la traccia, la soluzione e il tracciamento sulla carta. Tredici appendici, 489 slide: correnti, nomi della barca, nodi, segnali IALA, normativa, radio VHF, navigazione sottocosta, meteo, soccorso, ancoraggio e portanza. Venti prove d'esame simulate complete, dieci entro e dieci oltre 12 miglia, con le soluzioni. La prova pratica spiegata manovra per manovra, secondo l'Allegato D. E quindici schede riassuntive da stampare per gli allievi. In pratica: si accende il proiettore e si salpa. I deck si proiettano dal browser e si possono scaricare in PDF o PowerPoint.",
'perche':"[60 secondi · minuto 7:40] Per chiudere, sei ragioni per scegliere questo corso. È allineato all'esame: segue il programma del DM 323 del 2021 e usa quiz ed esercizi dell'elenco ufficiale del decreto dirigenziale 131 del 2022. Nessun esercizio resta indietro: 135 esercizi di carteggio su 135, svolti e tracciati. Si impara guardando: ogni lezione ha disegni originali di barche, manovre, carte, luci e segnali. La verifica è continua: quiz ufficiali in ogni lezione, sempre seguiti dalla slide con le risposte. È aggiornato: le dotazioni di sicurezza seguono il DM 133 del 2024. Ed è pronto per la scuola: note per l'istruttore, PDF e PowerPoint, schede da dare agli allievi. Pronti a salpare? Grazie, sono a disposizione per le vostre domande.",
}
tot=0
for i,t in N.items():
    f=f'{P}/slides/{i}.html'; s=open(f).read()
    assert s.count('<aside>')==1, i
    assert len(t)<=4000, (i,len(t))
    s=re.sub(r'<aside>.*?</aside>','<aside>'+t.replace('\\','\\\\')+'</aside>',s,flags=re.S)
    open(f,'w').write(s); tot+=len(re.sub(r'^\[[^\]]*\]\s*','',t).split())
print(len(N),'note,',tot,'parole')
