"""Note del relatore per l'indice del corso: presentazione completa in circa 15 minuti."""
import os, re, sys
SP=os.path.dirname(os.path.abspath(__file__))
P=sys.argv[1] if len(sys.argv)>1 else SP+'/deck/project'
N={
'cover':"[30 secondi · minuto 0:30] Buongiorno. Vi presento il corso per la patente nautica vela e motore senza limiti dalla costa, categoria A. In queste slide vedrete come è costruito: da quali norme parte, com'è fatto l'esame, le 15 lezioni da 2 ore, cioè 30 ore in aula, le 13 appendici di ripasso e il materiale per gli allievi. I numeri in basso riassumono tutto: 9 lezioni di teoria e vela, 6 di carteggio, i 135 esercizi d'esame e 13 appendici.",
'fonti':"[40 secondi · minuto 1:10] Il corso non segue un libro di testo ma quattro atti ufficiali. Il Codice della nautica da diporto, decreto legislativo 171 del 2005, stabilisce quando serve la patente e le sue categorie. Il regolamento di attuazione, DM 146 del 2008, contiene le dotazioni di sicurezza, riscritte dal DM 133 del 2024. Il DM 323 del 2021 è il decreto ministeriale sugli esami: l'Allegato A è il programma, l'Allegato C la scheda dei quiz per tema, l'Allegato D le esercitazioni pratiche. Infine il DD 131 del 2022, cioè il decreto dirigenziale con l'elenco unico nazionale: 1.472 quiz base, 250 quiz vela e 135 esercizi di carteggio. Ogni lezione cita l'argomento dell'Allegato A e ogni esercizio porta il suo numero ufficiale. Dove una domanda dell'elenco non è ancora aggiornata alle norme nuove, all'esame vale la risposta dell'elenco.",
'esame':"[50 secondi · minuto 2:00] L'esame, secondo gli articoli 3 e 6 del DM 323, ha una parte scritta e una pratica, in giorni diversi e con commissioni diverse. Si apre con il carteggio: 60 minuti, 4 esercizi sulla carta 5/D o 42/D, e se ne devono risolvere almeno 3. È propedeutico: senza carteggio non si prosegue. Poi quiz base e quiz vela in un unico blocco da 45 minuti: 20 quiz base con al massimo 4 errori, 5 quiz vela con al massimo 1 errore. Una risposta lasciata in bianco conta come errore. Le carte si portano integre e si consegnano all'appello. La prova pratica si fa un altro giorno, a motore e a vela; per esservi ammessi servono almeno 5 ore di manovre certificate da una scuola nautica. Chi ha già la patente entro 12 miglia non rifà i quiz base.",
'struttura':"[30 secondi · minuto 3:30] Ecco le quindici lezioni. Le prime nove, 18 ore, portano alla patente entro 12 miglia: scafo, motori, ormeggi e carte, ancoraggio, punto nave e fanali, segnalamento, sicurezza ed emergenze, meteo e normativa, poi la lezione 8 tutta dedicata alla prova di carteggio entro 12 miglia, e infine la lezione 9, tutta di vela. Le ultime sei, 12 ore, sono il carteggio oltre le 12 miglia: navigazione costiera, carburante, scarroccio, due lezioni sulle correnti e la carta 42/D. Il carteggio entro 12 miglia si costruisce nelle lezioni 3, 4 e 5 e si prova nella 8 sugli esercizi ufficiali. Le etichette dicono chi segue ogni lezione: la vela è concentrata nella 9, così chi fa solo motore la salta senza perdere nulla. Quattro percorsi: entro 12 miglia motore, lezioni 1-8, 16 ore; entro 12 miglia vela e motore, 1-9, 18 ore; senza limiti motore, tutte tranne la 9, 28 ore; senza limiti vela e motore, tutte e 15, 30 ore.",
'pesi':"[45 secondi · minuto 4:15] Come abbiamo distribuito il tempo? Seguendo il peso di ogni tema all'esame. L'Allegato C fissa quante domande arrivano da ogni tema sui 20 quiz base. Navigazione cartografica ed elettronica vale 4 domande e ha il bacino più grande, 322 quiz ufficiali; manovre e condotta vale 4; sicurezza e normativa 3 ciascuna; COLREG, segnalamento e meteorologia 2; teoria dello scafo e motori 1 ciascuna. A destra vedete in quali lezioni si tratta ogni tema. I quiz vela sono una prova a parte: 5 domande estratte da 250, trattate nella lezione 9. Le barre mostrano quanti quiz ufficiali ci sono da studiare per ogni tema.",
'l01':"[25 secondi · minuto 3:40] Lezione 1, teoria dello scafo, 1 domanda su 20 all'esame. Classificazione delle unità, dislocamento, carena, le parti dello scafo, ferramenta, assi e movimenti, flap e trim. Abbiamo aggiunto la stabilità: baricentro, centro di spinta e metacentro, che nel programma della scuola stava solo nelle lezioni di vela. Si chiude con i quiz ufficiali sulla teoria dello scafo.",
'l02':"[25 secondi · minuto 4:05] Lezione 2, motori, elica e timone. Il motore marino, la trasmissione, il quattro tempi e il diesel, il raffreddamento, i guasti tipici e come riconoscerli. Poi elica e timone: effetto evolutivo, elica destrorsa e sinistrorsa, bielica, tipi di timone, barra e ruota e i loro effetti combinati, che servono subito anche nella prova pratica.",
'l03':"[30 secondi · minuto 4:35] Lezione 3: ormeggi, cartografia e primi calcoli. Ormeggi e attracchi; latitudine e longitudine, miglio e nodo, i tipi di carte e le pubblicazioni nautiche, la proiezione di Mercatore e la lossodromia. Poi il primo carteggio: rosa dei venti, rotte, bussola, navigazione stimata e i calcoli di miglia, velocità e carburante, con gli esercizi d'esame che usano proprio questi calcoli.",
'l04':"[30 secondi · minuto 5:05] Lezione 4: ancoraggio, prora e rotta, 4 domande su 20 insieme agli altri temi di manovra e condotta. Cime e sistemi d'ormeggio, gavitelli, ancore, dar fondo e salpare, grippia e verifica della tenuta. Nel carteggio: rotta e prora vera, scarroccio e deriva, declinazione e deviazione. Abbiamo aggiunto la condotta sottocosta dell'Allegato A: limiti di velocità, zone di balneazione, corridoi di lancio e distanze dai subacquei.",
'l05':"[30 secondi · minuto 5:35] Lezione 5: punto nave e fanali. Navigazione costiera, rilevamenti, rilevamento polare, GPS: 4 domande su 20 dalla navigazione. Poi la prevenzione degli abbordi, altre 2 domande: tutti i fanali e le luci speciali, i segnali diurni che abbiamo aggiunto (pallone, cilindro, rombo, cono), la gerarchia delle precedenze a motore e a vela e il rischio di collisione.",
'l06':"[30 secondi · minuto 7:05] Lezione 6: segnalamento, segnali sonori e sicurezza. Simboli delle carte, elenco dei fari, caratteristiche e portate, il sistema IALA con laterali, cardinali, pericolo isolato, acque sicure e segnali speciali. Poi i segnali sonori e il comportamento all'ingresso e all'uscita dei porti. Infine la sicurezza, 3 domande su 20: le dotazioni obbligatorie per distanza dalla costa, aggiornate al DM 133 del 2024, l'incendio e, subito dopo, le emergenze: falla, incaglio, collisione, uomo a mare, abbandono, radio VHF, soccorso e cattivo tempo, con il CIRM e le regole su alcol e sostanze. È la lezione più densa: 42 slide.",
'l07':"[30 secondi · minuto 6:35] Lezione 7: meteorologia e normativa. Pressione, vento e brezze, fronti, nubi, nebbia, onde, maree, Meteomar e previsioni: 2 domande su 20. Poi la normativa, 3 domande: patenti, classificazione delle unità, documenti, visite e certificati di sicurezza, marcatura CE, autorità marittima e ordinanze, doveri del comandante, aree protette, sci nautico, noleggio e sanzioni.",
'l08':"[30 secondi · minuto 8:00] Lezione 8, per tutti: è l'ultima lezione della patente entro 12 miglia a motore. Tutta la lezione è dedicata alla prova di carteggio entro 12 miglia: un esercizio dell'elenco ufficiale con 5 quesiti in 20 minuti. Si riprendono gli strumenti e si affronta un quesito alla volta, coordinate, distanza, ora o velocità e carburante, con il metodo e gli errori tipici; poi quattro esercizi ufficiali risolti sulla carta 5/D e una prova simulata a cronometro. Le emergenze sono passate nella lezione 6.",
'l09':"[25 secondi · minuto 8:30] Lezione 9, la vela: solo per chi prende la patente a vela, chi fa solo motore la salta. Prepara ai 5 quiz vela. Prima l'attrezzatura: albero, boma, manovre fisse e correnti, lati e angoli delle vele, come si armano, vele di prua e nodi. Poi teoria e manovre: vento apparente e reale, centro velico e centro di deriva, andature, orzare e poggiare, regolazione, virata e abbattuta, terzaroli, panna e precedenze. Chiude un ripasso in otto flash.",
'carteggio':"[40 secondi · minuto 8:45] Le sei lezioni di carteggio hanno un obiettivo preciso: svolgere in aula tutti i 135 esercizi ufficiali, 108 sulla carta 5/D, Elba, Pianosa, Giglio e Argentario, e 27 sulla 42/D, le Bocche di Bonifacio. Sono di quattro famiglie: correnti, 52 esercizi, nelle lezioni 13, 14 e 15; navigazione costiera, 36, nelle lezioni 10 e 15; scarroccio, 24, nella lezione 12; carburante, 23, solo sulla 5/D, nella lezione 11. All'esame nessun esercizio sarà nuovo per l'allievo.",
'metodo':"[35 secondi · minuto 9:20] Ogni esercizio si svolge sempre allo stesso modo, in quattro passi. La traccia: il testo ministeriale parola per parola, con carta e settore. La soluzione: conversioni di prora, triangolo delle velocità, calcoli di tempo, spazio e consumo. Il tracciamento: la sequenza di linee e punti sulla carta, con gli orari. La verifica: il confronto con la risposta ufficiale e con la sua tolleranza. In basso un esempio, il 5.1.3-1: rilevamenti successivi del faro di Punta Polveraia, e la risposta ufficiale espressa come intervallo di coordinate.",
'l10':"[25 secondi · minuto 9:45] Lezione 10, navigazione costiera sulla 5/D: 26 esercizi, famiglie 5.1.3, 5.2.3, 5.3.3 e 5.4.3, uno per settore. Le tecniche: da prora bussola a prora vera con la declinazione aggiornata all'anno, punto nave con rilevamenti successivi sulla stessa mira o su mire diverse, punto da coordinate GPS. Nella maggior parte si chiede il punto raggiunto; alcuni l'intercettazione o la prora da tenere.",
'l11':"[20 secondi · minuto 10:05] Lezione 11, carburante e autonomia: 23 esercizi, tutti sulla 5/D, famiglie 5.x.2. Rilevamenti polari successivi, punto al traverso, e soprattutto il conto del carburante: tempo, consumo orario e riserva del 30 per cento. Tutti i 23 esercizi chiedono l'autonomia o il carburante necessario.",
'l12':"[25 secondi · minuto 10:30] Lezione 12, scarroccio: 24 esercizi, 20 sulla 5/D e i primi 4 sulla 42/D. Dalla prora vera alla rotta vera con l'angolo di scarroccio, il punto al traverso, il punto nave con rilevamento e distanza. Si chiede soprattutto il punto raggiunto, poi l'ora di arrivo, rotta e velocità, la prora da tenere. È anche il primo contatto con la carta delle Bocche di Bonifacio.",
'l13':"[25 secondi · minuto 10:55] Lezione 13, correnti prima parte: 21 esercizi nei settori A, B e C della 5/D. Il cuore è il triangolo delle velocità, poi come ricavare la corrente dal punto osservato, il punto nave con due rilevamenti simultanei o con rilevamento e distanza. Quattordici esercizi su ventuno chiedono proprio di trovare la corrente.",
'l14':"[25 secondi · minuto 11:20] Lezione 14, correnti seconda parte: 18 esercizi, tutti nel settore D della 5/D, famiglia 5.4.1. Qui la corrente è nota e si lavora al contrario: la prora da tenere, la velocità propulsiva necessaria, l'ora di arrivo, rotta e velocità effettive. È la lezione con i problemi più vari, per questo ha due ore dedicate.",
'l15':"[25 secondi · minuto 11:45] Lezione 15, la carta 42/D delle Bocche di Bonifacio: 23 esercizi, 10 di navigazione costiera e 13 di correnti, nei quattro settori della carta. Due rilevamenti simultanei, punto di intercettazione, prora da tenere, corrente dal punto. Si chiude il corso applicando su una carta nuova tutto quello che si è fatto sulla 5/D.",
'appendici1':"[45 secondi · minuto 12:30] Oltre alle lezioni ci sono tredici appendici, deck separati per il ripasso e l'esercitazione. Le prime sei: A, i tre problemi della corrente con il metodo passo per passo; B, tutti i nomi della barca a vela; C, i nodi del programma d'esame disegnati passo per passo; D, dieci prove d'esame simulate complete di carteggio, quiz base e quiz vela, con le soluzioni, 105 slide; E, la prova pratica manovra per manovra; F, le schede dei segnali IALA. Il numero di slide di ognuna è indicato a destra.",
'appendici2':"[45 secondi · minuto 13:15] Le altre sette: G, la normativa in tabelle, da consultare a colpo d'occhio; H, la radio VHF con le procedure di chiamata e di soccorso; I, la navigazione sottocosta; J, i bollettini meteo e come decidere se uscire; K, il soccorso in mare; L, l'ancoraggio. L'ultima, M, spiega la portanza: perché un'ala vola e perché una vela spinge la barca controvento, con disegni del flusso calcolati, i contenuti del capitolo 4 di Laura Romanò, «La fisica in barca a vela», e il confronto con quello che si legge sul web. Ogni appendice ha le sue verifiche con i quiz ufficiali.",
'extra':"[35 secondi · minuto 13:50] Due materiali in più. A sinistra la presentazione del corso alla scuola: sette slide sulla struttura, sui percorsi entro 12 miglia e senza limiti, sulla differenza tra vela e motore e solo motore, sulle competenze e sui punti di forza. A destra le schede riassuntive per gli allievi, da stampare: una o due pagine per lezione con le regole da memorizzare, i numeri che tornano nei quiz e le formule del carteggio. I collegamenti sono nelle schede.",
'prossimi':"[60 secondi · minuto 14:50] Riassumendo: 15 lezioni da 2 ore, 13 appendici, 10 prove d'esame simulate e tutti i 135 esercizi di carteggio svolti. Come si usa tutto questo? In aula le slide della lezione, con disegni, schemi e quiz ufficiali seguiti dalle risposte. A casa le appendici e le schede riassuntive per ripassare. Prima dell'esame le 10 prove simulate e il ripasso della prova pratica. E per presentare il corso, la sintesi in sette slide. Tutto è pronto, si proietta dal browser e si scarica in PDF o PowerPoint. Grazie, sono a disposizione per le domande.",
}
tot=0
for i,t in N.items():
    f=f'{P}/slides/{i}.html'; s=open(f).read()
    assert s.count('<aside>')==1, i
    assert len(t)<=4000, (i,len(t))
    s=re.sub(r'<aside>.*?</aside>','<aside>'+t.replace('\\','\\\\')+'</aside>',s,flags=re.S)
    open(f,'w').write(s); tot+=len(re.sub(r'^\[[^\]]*\]\s*','',t).split())
print(len(N),'note,',tot,'parole')
